name: Autoversion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/autoversion@09172e83f9d0372b01fc3845f952135b9a208a4f # v3.1.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          openai_token: ${{ secrets.OPENAI_API_TOKEN }}
    permissions:
      actions: read
