name: Autoversion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # TODO adjust schedule

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/autoversion@v0.17.1
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          openai_token: ${{ secrets.OPENAI_TOKEN }} # TODO remove if no token is available
