name: Autorerun

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/autorerun@01cbbd02fa9641d3e243b12190be63c7aa3a13c5 # v0.38.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    permissions:
      actions: read
