name: Autoversion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/autoversion@075d9850ed89b6683b71ecab1e4ad873a28dc61e # v3.0.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          openai_token: ${{ secrets.OPENAI_API_TOKEN }}
    permissions:
      actions: read
