name: Autoversion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/autoversion@c52ec7d4869f199d2b1706059fb4f9d15eb672b9 # v3.1.1
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          openai_token: ${{ secrets.OPENAI_API_TOKEN }}
    permissions:
      actions: read
