name: Publish

on:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish.yml
      
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: plengauer/create-deb-repository@a4d6f9716b10ba903bb511e1b301a056a85323bf # v0.1.0
      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: .
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
